# Plants.gd
extends Node

const EFFECTS = [
	"Restore Stamina", "Increase Weapon Power", "Speed", "Restore Health", "Invisible", "Increase Spell Resist", "Unstoppable", "Increase Spell Power", "Detection", "Restore Magicka", "Weapon Crit", "Protection", "Spell Crit", "Vitality", "Lingering Health", "Sustained Restore Health", "Increase Armor"
]

const PLANTS = {
	"Torchbug Thorax": ["Increase Weapon Power", "Lower Weapon Crit", "Lower Spell Power", "Restore Stamina"],
	"Blue Entoloma": ["Lower Spell Resist", "Increase Spell Resist", "Increase Armor", "Weapon Crit"],
	"Clam Gall": ["Vulnerability", "Weapon Crit", "Speed", "Lower Spell Resist"],
	"Hagraven Feathers": ["Increase Spell Power", "Lingering Health", "Ravage Health", "Weapon Crit"],
	"Grass Pod": ["Lower Spell Crit", "Lower Weapon Power", "Weapon Crit", "Unstoppable"],
	"Salmon Roe": ["Lower Spell Power", "Creeping Ravage Health", "Cowardice", "Lower Spell Crit"],
	"Blue Dartwing": ["Entrapment", "Increase Spell Resist", "Defile", "Protection"],
	"River Betty": ["Ravage Magicka", "Lower Weapon Crit", "Increase Weapon Power", "Lower Spell Power"],
	"Vampire Dust": ["Restore Stamina", "Lower Weapon Power", "Increase Armor", "Entrapment"],
	"Fleshfly Larva": ["Reduce Speed", "Lower Weapon Power", "Lower Weapon Crit", "Defile"],
	"Blisterwort": ["Invisible", "Spell Crit", "Protection", "Vulnerability"],
	"Histcarp": ["Creeping Ravage Health", "Cowardice", "Increase Spell Resist", "Detection"],
	"Nightshade": ["Increase Weapon Power", "Lingering Health", "Defile", "Increase Spell Resist"],
	"Large Antlers": ["Entrapment", "Lower Spell Crit", "Protection", "Spell Crit"],
	"Salt Pile": ["Ravage Health", "Increase Armor", "Spell Crit", "Restore Health"],
	"Slaughterfish Scales": ["Vitality", "Entrapment", "Ravage Magicka", "Increase Spell Power"],
	"Columbine": ["Ravage Health", "Restore Health", "Ravage Magicka", "Spell Crit"],
	"Gleamblossom": ["Vulnerability", "Speed", "Ravage Health", "Restore Health"],
	"Dragon's Tongue": ["Increase Spell Resist", "Lower Weapon Crit", "Detection", "Vitality"],
	"Water Hyacinth": ["Lower Spell Crit", "Ravage Magicka", "Lower Weapon Power", "Weapon Crit"],
	"Ectoplasm": ["Unstoppable", "Vitality", "Defile", "Increase Weapon Power"],
	"Fly Amanita": ["Defile", "Lower Armor", "Protection", "Weapon Crit"],
	"Cyrodilic Spadetail": ["Sustained Restore Health", "Lower Spell Power", "Vulnerability", "Restore Stamina"],
	"Blue Mountain Flower": ["Vitality", "Lower Spell Resist", "Sustained Restore Health", "Spell Crit"],
	"Spawn Ash": ["Cowardice", "Lower Spell Resist", "Increase Spell Power", "Increase Armor"],
	"Jarrin Root": ["Speed", "Gradual Ravage Health", "Reduce Speed", "Weapon Crit"],
	"Lady's Smock": ["Entrapment", "Lingering Health", "Vulnerability", "Restore Stamina"],
	"Ashen Grass Pod": ["Spell Crit", "Speed", "Weapon Crit", "Gradual Ravage Health"],
	"Rock Warbler Egg": ["Invisible", "Lower Armor", "Unstoppable", "Restore Health"],
	"Jazbay Grapes": ["Lower Weapon Power", "Creeping Ravage Health", "Gradual Ravage Health", "Invisible"],
	"Butterfly Wing": ["Entrapment", "Vulnerability", "Cowardice", "Defile"],
	"Pine Thrush Egg": ["Spell Crit", "Invisible", "Increase Weapon Power", "Speed"],
	"Bugloss": ["Lower Spell Resist", "Increase Spell Resist", "Increase Spell Power", "Unstoppable"],
	"Swamp Fungal Pod": ["Lower Spell Power", "Restore Health", "Creeping Ravage Health", "Ravage Health"],
	"Spriggan Sap": ["Increase Spell Power", "Vulnerability", "Protection", "Restore Health"],
	"Falmer Ear": ["Gradual Ravage Health", "Creeping Ravage Health", "Lingering Health", "Ravage Magicka"],
	"Skeever Tail": ["Defile", "Ravage Health", "Lower Spell Power", "Speed"],
	"Wheat": ["Reduce Speed", "Entrapment", "Protection", "Ravage Magicka"],
	"Deathbell": ["Increase Armor", "Increase Weapon Power", "Increase Spell Resist", "Unstoppable"],
	"Powdered Mother of Pearl": ["Lower Spell Crit", "Invisible", "Increase Armor", "Speed"],
	"Mudcrab Chitin": ["Lower Spell Power", "Lower Weapon Power", "Ravage Magicka", "Restore Health"],
	"Elves Ear": ["Increase Weapon Power", "Cowardice", "Entrapment", "Ravage Health"],
	"Small Pearl": ["Protection", "Spell Crit", "Unstoppable", "Reduce Speed"],
	"Scrib Jelly": ["Lingering Health", "Lower Spell Crit", "Protection", "Increase Spell Power"],
	"Giant Lichen": ["Invisible", "Lower Spell Resist", "Creeping Ravage Health", "Ravage Magicka"],
	"BlueLeaf": ["Lingering Health", "Increase Spell Power", "Protection", "Invisible"],
	"AncientFungus": ["Invisible", "Detection", "Weapon Crit", "Spell Crit"],
	"NightBark": ["Sustained Restore Health", "Lower Spell Power", "Restore Health", "Ravage Magicka"],
	"FrostVine": ["Restore Stamina", "Speed", "Invisible", "Vitality"],
	"ShadowRoot": ["Increase Spell Power", "Detection", "Spell Crit", "Lingering Health"],
	"SunRoot": ["Restore Health", "Increase Armor", "Unstoppable", "Weapon Crit"],
	"MoonFlower": ["Invisible", "Lower Spell Resist", "Vitality", "Spell Crit"],
	"ThunderLeaf": ["Speed", "Increase Weapon Power", "Detection", "Restore Stamina"],
	"StarThistle": ["Protection", "Sustained Restore Health", "Increase Spell Resist", "Lingering Health"],
	"EmberBerry": ["Increase Spell Power", "Weapon Crit", "Restore Magicka", "Vitality"],
	"IceCap": ["Reduce Speed", "Increase Armor", "Unstoppable", "Lower Weapon Crit"],
	"FlamePetals": ["Creeping Ravage Health", "Increase Weapon Power", "Speed", "Ravage Health"],
	"VoidBloom": ["Lower Spell Power", "Invisible", "Cowardice", "Defile"],
	"EchoHerb": ["Detection", "Spell Crit", "Lower Spell Resist", "Restore Health"],
	"CrystalVine": ["Vitality", "Increase Spell Resist", "Protection", "Gradual Ravage Health"],
	"GhostMoss": ["Invisible", "Lingering Health", "Lower Weapon Power", "Unstoppable"],
	"SolarNettle": ["Increase Armor", "Weapon Crit", "Speed", "Restore Stamina"],
	"LunarFern": ["Restore Magicka", "Spell Crit", "Increase Spell Power", "Detection"],
	"AuroraRoot": ["Sustained Restore Health", "Vitality", "Lower Spell Crit", "Protection"],
	"StormWeed": ["Increase Weapon Power", "Speed", "Weapon Crit", "Reduce Speed"],
	"DawnBlossom": ["Restore Health", "Lingering Health", "Increase Spell Resist", "Invisible"],
	"TwilightThorn": ["Defile", "Ravage Magicka", "Cowardice", "Lower Armor"],
	"EternalSprout": ["Unstoppable", "Vitality", "Increase Armor", "Spell Crit"],
	"MysticThistle": ["Restore Stamina", "Speed", "Invisible", "Vitality"],
	"AncientBloom": ["Increase Spell Power", "Detection", "Spell Crit", "Lingering Health"]
}
